= Gate interlock

If you require a pair of interlocked gates or doors, eg to create an anti tailgate solution, you will have no doubt found many flaws in the existing easily affordable/accessible solutions.  The particular set of gates I was working with were incapable of talking to each other and the access control system has no concept of an interlocked door.

An arduino should be capable of bridging the gap between access control and the gates creating an interlocked pair of doors and provide a more flexible and easier to maintain system than a proprietary solution from either an access control provider or from a motor provider.

The code is designed for an arduino nano, but with some PIN changes should be easy enough to use on most microcontrollers.

== Definitions
Outer Gate:: The insecure side of the interlocked doors/gates
Inner Gate:: The secure side of the interlocked doors/gates
Inbound:: Going from the outer side, to the inner side.
Outbound:: Going from the inner side to the outer side.

== Inputs/Outputs

[discrete]
== Inputs
- Inbound access approved
- Outbound access approved
- User is stuck in between inner and outer gates
- Outer gate is closed
- Inner gate is closed

[discrete]
== Outputs
- Outer gate open request
- Inner gate open request

[discrete]
== Status indicators
 - Outer gate is closed
 - Inner gate is closed
 - Outer gate is opening or closing
 - Inner gate is opening or closing
 - Inbound cycle in progress
 - Outbound cycle in progress
 - Combined gate open

[discrete]
== Jumpers
- Outer gate disabled
- Inner gate disabled

== Logic
- It is assumed gates auto close.
- When the first gate in the interlock closes, the second will open automatically.
- Only a single gate is allowed to be open at a time.
- If the user requests access at a gate that is closing, the gate will be opened and the cycle started.
- If the user requests access and the opposite gate is still closing, ths signal will be ignored.footnote:buffer[I may add a small buffer window for this so the cycle will start immediately upon closure]
- If the user is stuck, if either gate is already open this gate will be opened.
- If the user is stuck and neither gate is open the outer gate will be opened.
- If the user is stuck, they user should exit via the opened gate, or they will become trapped again.
- If a gate is requested to open, and it doesn't open this times out  and the system goes idle.footnote:opentimeout[5 seconds]
- If a gate fails to open and shut, this times out and the system goes idle.footnote:closetimeout[2 minutes]
